[package]
name = "battery"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
eyre = "0.6.12"
maplit = "1.0.2"
rustls = { version = "0.23.35", features = ["ring"] }
s2energy = { git = "https://github.com/flexiblepower/s2-rust.git", branch = "kiflin" }
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
uuid = { version = "1.16.0", features = ["v4"] }
